- name: Install required packages
  apt: pkg={{ item }} state=present
  with_items:
    - hylafax-server
    - hylafax-client

- name: Remove /etc/cron.monthly/hylafax to stop monthly stats emails
  file:
    path: /etc/cron.monthly/hylafax
    state: absent
